<a href="https://colab.research.google.com/github/mdruwaid/college-labs/blob/main/DL-labs/2_program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
x_train = x_train/255.0
x_test = x_test/255.0

In [5]:
y_train= to_categorical(y_train,10)
y_test= to_categorical(y_test,10)

In [7]:
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(512,activation='relu'),
    Dense(256,activation='relu'),
    Dense(128,activation='relu'),
    Dense(10,activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.compile(optimizer = 'adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

In [10]:
histroy = model.fit(
    x_train,y_train,
    epochs = 5,
    batch_size = 128,
    validation_split = 0.1
)

Epoch 1/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - accuracy: 0.9283 - loss: 0.2461 - val_accuracy: 0.9690 - val_loss: 0.1051
Epoch 2/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - accuracy: 0.9721 - loss: 0.0877 - val_accuracy: 0.9782 - val_loss: 0.0779
Epoch 3/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 8s 19ms/step - accuracy: 0.9819 - loss: 0.0577 - val_accuracy: 0.9787 - val_loss: 0.0763
Epoch 4/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - accuracy: 0.9865 - loss: 0.0421 - val_accuracy: 0.9778 - val_loss: 0.0732
Epoch 5/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 8s 19ms/step - accuracy: 0.9894 - loss: 0.0322 - val_accuracy: 0.9772 - val_loss: 0.0891


In [11]:
test_loss, test_acc = model.evaluate(x_test, y_test, verbose = 2)
print(f"\nTest accuracy : {test_acc:.4f}")

313/313 - 1s - 5ms/step - accuracy: 0.9760 - loss: 0.0907

Test accuracy : 0.9760


In [12]:
import numpy as np

In [14]:
sample = x_test[0].reshape(1,28,28)
prediction = np.argmax(model.predict(sample))
print(f"Predicted digit: {prediction}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
Predicted digit: 7


In [15]:
from tensorflow.keras.callbacks import EarlyStopping
callbacks = [EarlyStopping(monitor = 'val_loss',patience = 3, restore_best_weights = True)]
histroy = model.fit(x_train,y_train, epochs = 30, batch_size = 128, validation_split=0.1,callbacks = callbacks)


Epoch 1/30
422/422 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9915 - loss: 0.0262 - val_accuracy: 0.9835 - val_loss: 0.0609
Epoch 2/30
422/422 ━━━━━━━━━━━━━━━━━━━━ 16s 29ms/step - accuracy: 0.9920 - loss: 0.0230 - val_accuracy: 0.9827 - val_loss: 0.0699
Epoch 3/30
422/422 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9931 - loss: 0.0205 - val_accuracy: 0.9777 - val_loss: 0.0967
Epoch 4/30
422/422 ━━━━━━━━━━━━━━━━━━━━ 12s 27ms/step - accuracy: 0.9948 - loss: 0.0166 - val_accuracy: 0.9787 - val_loss: 0.0902


In [17]:
import numpy as np
from sklearn.metrics import confusion_matrix , classification_report
y_prob = model.predict(x_test)
y_pred = np.argmax(y_prob,axis = 1)
y_true = np.argmax(y_test,axis = 1)
print(confusion_matrix(y_true,y_pred))
print(classification_report(y_true,y_pred))

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step
[[ 972    1    0    2    0    1    2    0    1    1]
 [   0 1126    4    0    0    1    1    1    2    0]
 [   4    0 1003    6    2    0    1    4   11    1]
 [   0    0    1  994    1    5    0    1    6    2]
 [   2    0    0    1  965    1    3    1    0    9]
 [   1    0    0   11    1  871    3    0    3    2]
 [   3    2    3    1    3    9  932    2    3    0]
 [   0    0    6    2    2    0    0 1007    3    8]
 [   0    0    0    3    5    4    0    2  956    4]
 [   1    2    1    4   10    5    0    2    0  984]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       1.00      0.99      0.99      1135
           2       0.99      0.97      0.98      1032
           3       0.97      0.98      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.97      0.98      0.97       892
           6       0.99      0.97      0.98      